title:              Strategic Analytics and AI
email:              vijay.dakshinamoorthy@gmail.com
description:        Applications of Data Science and Machine Learning
author:             Vijay Dakshinamoorthy
baseurl:            "/"
url:                "https://vdakshin.github.io"

# Social Profiles
twitter_username:   vdakshin
github_username:    vdakshin
facebook_username:  vdakshin
linkedin_username:  vijaydakshinamoorthy

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-145152335-1 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-seo-tag
#gems:
#  - jekyll-feed
#  - jekyll-paginate
#  - jekyll-sitemap

#whitelist:
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
  - jemoji